deweloper:
    path:     /
    defaults: { _controller: "AppBundle:Deweloper:index" }

deweloper_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Deweloper:show" }

deweloper_new:
    path:     /new
    defaults: { _controller: "AppBundle:Deweloper:new" }

deweloper_create:
    path:     /create
    defaults: { _controller: "AppBundle:Deweloper:create" }
    methods:  POST

deweloper_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Deweloper:edit" }

deweloper_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Deweloper:update" }
    methods:  [POST, PUT]

deweloper_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Deweloper:delete" }
    methods:  [POST, DELETE]
