filmrezyser:
    path:     /
    defaults: { _controller: "AppBundle:FilmRezyser:index" }

filmrezyser_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:FilmRezyser:show" }

filmrezyser_new:
    path:     /new
    defaults: { _controller: "AppBundle:FilmRezyser:new" }

filmrezyser_create:
    path:     /create
    defaults: { _controller: "AppBundle:FilmRezyser:create" }
    methods:  POST

filmrezyser_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:FilmRezyser:edit" }

filmrezyser_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:FilmRezyser:update" }
    methods:  [POST, PUT]

filmrezyser_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:FilmRezyser:delete" }
    methods:  [POST, DELETE]
