film:
    path:     /
    defaults: { _controller: "AppBundle:Film:index" }

film_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Film:show" }

film_new:
    path:     /new
    defaults: { _controller: "AppBundle:Film:new" }

film_create:
    path:     /create
    defaults: { _controller: "AppBundle:Film:create" }
    methods:  POST

film_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Film:edit" }

film_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Film:update" }
    methods:  [POST, PUT]

film_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Film:delete" }
    methods:  [POST, DELETE]
