gra:
    path:     /
    defaults: { _controller: "AppBundle:Gra:index" }

gra_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Gra:show" }

gra_new:
    path:     /new
    defaults: { _controller: "AppBundle:Gra:new" }

gra_create:
    path:     /create
    defaults: { _controller: "AppBundle:Gra:create" }
    methods:  POST

gra_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Gra:edit" }

gra_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Gra:update" }
    methods:  [POST, PUT]

gra_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Gra:delete" }
    methods:  [POST, DELETE]
