ksiazka:
    path:     /
    defaults: { _controller: "AppBundle:Ksiazka:index" }

ksiazka_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Ksiazka:show" }

ksiazka_new:
    path:     /new
    defaults: { _controller: "AppBundle:Ksiazka:new" }

ksiazka_create:
    path:     /create
    defaults: { _controller: "AppBundle:Ksiazka:create" }
    methods:  POST

ksiazka_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Ksiazka:edit" }

ksiazka_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Ksiazka:update" }
    methods:  [POST, PUT]

ksiazka_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Ksiazka:delete" }
    methods:  [POST, DELETE]
