ocena:
    path:     /
    defaults: { _controller: "AppBundle:Ocena:index" }

ocena_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Ocena:show" }

ocena_new:
    path:     /new
    defaults: { _controller: "AppBundle:Ocena:new" }

ocena_create:
    path:     /create
    defaults: { _controller: "AppBundle:Ocena:create" }
    methods:  POST

ocena_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Ocena:edit" }

ocena_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Ocena:update" }
    methods:  [POST, PUT]

ocena_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Ocena:delete" }
    methods:  [POST, DELETE]
