uzytkownik:
    path:     /
    defaults: { _controller: "AppBundle:Uzytkownik:index" }

uzytkownik_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Uzytkownik:show" }

uzytkownik_new:
    path:     /new
    defaults: { _controller: "AppBundle:Uzytkownik:new" }

uzytkownik_create:
    path:     /create
    defaults: { _controller: "AppBundle:Uzytkownik:create" }
    methods:  POST

uzytkownik_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Uzytkownik:edit" }

uzytkownik_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Uzytkownik:update" }
    methods:  [POST, PUT]

uzytkownik_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Uzytkownik:delete" }
    methods:  [POST, DELETE]
