uzytkownikocenaksiazka:
    path:     /
    defaults: { _controller: "AppBundle:UzytkownikOcenaKsiazka:index" }

uzytkownikocenaksiazka_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:UzytkownikOcenaKsiazka:show" }

uzytkownikocenaksiazka_new:
    path:     /new
    defaults: { _controller: "AppBundle:UzytkownikOcenaKsiazka:new" }

uzytkownikocenaksiazka_create:
    path:     /create
    defaults: { _controller: "AppBundle:UzytkownikOcenaKsiazka:create" }
    methods:  POST

uzytkownikocenaksiazka_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:UzytkownikOcenaKsiazka:edit" }

uzytkownikocenaksiazka_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:UzytkownikOcenaKsiazka:update" }
    methods:  [POST, PUT]

uzytkownikocenaksiazka_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:UzytkownikOcenaKsiazka:delete" }
    methods:  [POST, DELETE]
