AppBundle\Entity\Film:
    type: entity
    table: film
    indexes:
        fk_Film_Gatunek1_idx:
            columns:
                - Gatunek_idGatunek1
        fk_film_rok_produkcji1_idx:
            columns:
                - rok_produkcji_idRokProdukcji
    id:
        idfilm:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idFilm
            generator:
                strategy: IDENTITY
    fields:
        tytul:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
    manyToOne:
        gatunekgatunek1:
            targetEntity: Gatunek
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                Gatunek_idGatunek1:
                    referencedColumnName: idGatunek
            orphanRemoval: false
        rokProdukcjirokprodukcji:
            targetEntity: RokProdukcji
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                rok_produkcji_idRokProdukcji:
                    referencedColumnName: idRokProdukcji
            orphanRemoval: false
    lifecycleCallbacks: {  }
