AppBundle\Entity\FilmRezyser:
    type: entity
    table: film_rezyser
    indexes:
        fk_Film_Rezyser_Film1_idx:
            columns:
                - Film_idFilm
        fk_Film_Rezyser_Rezyser1:
            columns:
                - Rezyser_idRezyser
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        rezyserrezyser:
            targetEntity: Rezyser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                Rezyser_idRezyser:
                    referencedColumnName: idRezyser
            orphanRemoval: false
        filmfilm:
            targetEntity: Film
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                Film_idFilm:
                    referencedColumnName: idFilm
            orphanRemoval: false
    lifecycleCallbacks: {  }
