AppBundle\Entity\OcenaUzytkownikKsiazka:
    type: entity
    table: ocena_uzytkownik_ksiazka
    indexes:
        fk_ocena_uzytkownik_ksiazka_ocena1_idx:
            columns:
                - ocena_idOcena
        fk_ocena_uzytkownik_ksiazka_ksiazka1_idx:
            columns:
                - ksiazka_idKsiazka
        fk_ocena_uzytkownik_ksiazka_fos_user1:
            columns:
                - fos_user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        ocenaocena:
            targetEntity: Ocena
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ocena_idOcena:
                    referencedColumnName: idOcena
            orphanRemoval: false
        fosUser:
            targetEntity: FosUser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fos_user_id:
                    referencedColumnName: id
            orphanRemoval: false
        ksiazkaksiazka:
            targetEntity: Ksiazka
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ksiazka_idKsiazka:
                    referencedColumnName: idKsiazka
            orphanRemoval: false
    lifecycleCallbacks: {  }
