AppBundle\Entity\OcenaUztkownikFilm:
    type: entity
    table: ocena_uztkownik_film
    indexes:
        fk_ocena_uztkownik_film_ocena1_idx:
            columns:
                - ocena_idOcena
        fk_ocena_uztkownik_film_film1_idx:
            columns:
                - film_idFilm
        fk_ocena_uztkownik_film_fos_user1:
            columns:
                - fos_user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        ocenaocena:
            targetEntity: Ocena
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ocena_idOcena:
                    referencedColumnName: idOcena
            orphanRemoval: false
        fosUser:
            targetEntity: FosUser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fos_user_id:
                    referencedColumnName: id
            orphanRemoval: false
        filmfilm:
            targetEntity: Film
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                film_idFilm:
                    referencedColumnName: idFilm
            orphanRemoval: false
    lifecycleCallbacks: {  }
