AppBundle\Entity\Producent:
    type: entity
    table: producent
    id:
        idproducent:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idProducent
            generator:
                strategy: IDENTITY
    fields:
        nazwa:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
    lifecycleCallbacks: {  }
