AppBundle\Entity\RecenzjaUzytkownikGra:
    type: entity
    table: recenzja_uzytkownik_gra
    indexes:
        fk_recenzja_uzytkownik_gra_recenzja1_idx:
            columns:
                - recenzja_idRecenzja
        fk_recenzja_uzytkownik_gra_gra1_idx:
            columns:
                - gra_idGra
        fk_recenzja_uzytkownik_gra_fos_user1:
            columns:
                - fos_user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        recenzjarecenzja:
            targetEntity: Recenzja
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                recenzja_idRecenzja:
                    referencedColumnName: idRecenzja
            orphanRemoval: false
        fosUser:
            targetEntity: FosUser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fos_user_id:
                    referencedColumnName: id
            orphanRemoval: false
        gragra:
            targetEntity: Gra
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                gra_idGra:
                    referencedColumnName: idGra
            orphanRemoval: false
    lifecycleCallbacks: {  }
