AppBundle\Entity\Recenzja:
    type: entity
    table: recenzja
    id:
        idrecenzja:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idRecenzja
            generator:
                strategy: IDENTITY
    fields:
        tresc:
            type: string
            nullable: false
            length: 1000
            options:
                fixed: false
    lifecycleCallbacks: {  }
