AppBundle\Entity\Rezyser:
    type: entity
    table: rezyser
    id:
        idrezyser:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idRezyser
            generator:
                strategy: IDENTITY
    fields:
        imie:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: Imie
        nazwisko:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: Nazwisko
    lifecycleCallbacks: {  }
