AppBundle\Entity\Uzytkownik:
    type: entity
    table: uzytkownik
    uniqueConstraints:
        user_id_UNIQUE:
            columns:
                - idUzytkownik
        login_UNIQUE:
            columns:
                - login
    id:
        iduzytkownik:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: idUzytkownik
            generator:
                strategy: IDENTITY
    fields:
        login:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
    lifecycleCallbacks: {  }
