AppBundle\Entity\UzytkownikOcenaFilm:
    type: entity
    table: uzytkownik_ocena_film
    indexes:
        fk_Uzytkownik_Ocena_Film_Ocena1_idx:
            columns:
                - Ocena_idOcena
        fk_Uzytkownik_Ocena_Film_Recenzja1_idx:
            columns:
                - Recenzja_idRecenzja
        fk_Uzytkownik_Ocena_Film_Film1_idx:
            columns:
                - Film_idFilm
        fk_Uzytkownik_Ocena_Film_Uzytkownik1:
            columns:
                - Uzytkownik_idUzytkownik
    id:
        idUzocfi:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_UzOcFi
    oneToOne:
        uzytkownikuzytkownik:
            targetEntity: Uzytkownik
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                Uzytkownik_idUzytkownik:
                    referencedColumnName: idUzytkownik
            orphanRemoval: false
        ocenaocena:
            targetEntity: Ocena
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                Ocena_idOcena:
                    referencedColumnName: idOcena
            orphanRemoval: false
        filmfilm:
            targetEntity: Film
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                Film_idFilm:
                    referencedColumnName: idFilm
            orphanRemoval: false
    manyToOne:
        recenzjarecenzja:
            targetEntity: Recenzja
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                Recenzja_idRecenzja:
                    referencedColumnName: idRecenzja
            orphanRemoval: false
    lifecycleCallbacks: {  }
