AppBundle\Entity\UzytkownikOcenaKsiazka:
    type: entity
    table: uzytkownik_ocena_ksiazka
    indexes:
        fk_Uzytkownik_Ocena_Ksiazka_Uzytkownik1_idx:
            columns:
                - Uzytkownik_idUzytkownik
        fk_Uzytkownik_Ocena_Ksiazka_Ksiazka1_idx:
            columns:
                - Ksiazka_idKsiazka
        fk_Uzytkownik_Ocena_Ksiazka_Recenzja1_idx:
            columns:
                - Recenzja_idRecenzja
        fk_Uzytkownik_Ocena_Ksiazka_Ocena1:
            columns:
                - Ocena_idOcena
    id:
        iduzocks:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idUzOcKs
            generator:
                strategy: IDENTITY
    manyToOne:
        ocenaocena:
            targetEntity: Ocena
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                Ocena_idOcena:
                    referencedColumnName: idOcena
            orphanRemoval: false
        uzytkownikuzytkownik:
            targetEntity: Uzytkownik
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                Uzytkownik_idUzytkownik:
                    referencedColumnName: idUzytkownik
            orphanRemoval: false
        ksiazkaksiazka:
            targetEntity: Ksiazka
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                Ksiazka_idKsiazka:
                    referencedColumnName: idKsiazka
            orphanRemoval: false
        recenzjarecenzja:
            targetEntity: Recenzja
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                Recenzja_idRecenzja:
                    referencedColumnName: idRecenzja
            orphanRemoval: false
    lifecycleCallbacks: {  }
